(() => {
  "use strict";
  const COLS=10, ROWS=20, COLORS={I:"#2ee7ed",J:"#4177ff",L:"#ff9b32",O:"#ffe145",S:"#42df78",T:"#bd64ff",Z:"#ff5267"};
  const SHAPES={I:[[0,0,0,0],[1,1,1,1],[0,0,0,0],[0,0,0,0]],J:[[1,0,0],[1,1,1],[0,0,0]],L:[[0,0,1],[1,1,1],[0,0,0]],O:[[1,1],[1,1]],S:[[0,1,1],[1,1,0],[0,0,0]],T:[[0,1,0],[1,1,1],[0,0,0]],Z:[[1,1,0],[0,1,1],[0,0,0]]};
  const TYPES=Object.keys(SHAPES);
  const $=id=>document.getElementById(id);
  const canvas=$("gameCanvas"),ctx=canvas.getContext("2d"),nextCtx=$("nextCanvas").getContext("2d"),holdCtx=$("holdCanvas").getContext("2d");
  const els={score:$("score"),best:$("best"),lines:$("lines"),level:$("level"),player:$("playerName"),message:$("centerMessage"),flash:$("flash"),nameModal:$("nameModal"),over:$("gameOverModal"),pause:$("pauseModal"),rank:$("rankModal"),final:$("finalScore"),status:$("resultStatus"),rankList:$("rankList"),sound:$("soundBtn")};
  const API_BASE=(window.DANNYBOY_API||"").replace(/\/$/,"");
  let board,piece,nextPiece,holdPiece,canHold,score,lines,level,best,state="welcome",dropTimer=0,lastTime=0,raf=0,bag=[],rankWasRunning=false,soundOn=localStorage.getItem("dannyboy-tetris-sound")!=="off",playerName=localStorage.getItem("dannyboy-tetris-name")||"",playerId=localStorage.getItem("dannyboy-tetris-id")||"";

  class AudioBox {
    constructor(){this.ctx=null;}
    unlock(){if(!soundOn)return; if(!this.ctx)this.ctx=new (window.AudioContext||window.webkitAudioContext)(); if(this.ctx.state==="suspended")this.ctx.resume();}
    tone(freq,dur,type="square",vol=.035,delay=0){if(!soundOn)return;this.unlock();if(!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+dur);}
    move(){this.tone(160,.035,"square",.018)} rotate(){this.tone(290,.055,"square",.025)} lock(){this.tone(95,.06,"square",.03)} clear(n){[523,659,784,1046].slice(0,Math.min(4,n+1)).forEach((f,i)=>this.tone(f,.16,"square",.045,i*.045))} over(){[260,210,160,105].forEach((f,i)=>this.tone(f,.24,"sawtooth",.035,i*.13))}
  }
  const audio=new AudioBox();
  function vibrate(ms){try{navigator.vibrate?.(ms)}catch{}}
  function emptyBoard(){return Array.from({length:ROWS},()=>Array(COLS).fill(""));}
  function clone(m){return m.map(r=>r.slice());}
  function newBag(){const a=TYPES.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}bag.push(...a)}
  function nextType(){if(bag.length<7)newBag();return bag.shift();}
  function makePiece(type=nextType()){const matrix=clone(SHAPES[type]);return{type,matrix,x:Math.floor((COLS-matrix[0].length)/2),y:-1};}
  function collision(test=piece,offX=0,offY=0,matrix=test.matrix){for(let y=0;y<matrix.length;y++)for(let x=0;x<matrix[y].length;x++)if(matrix[y][x]){const nx=test.x+x+offX,ny=test.y+y+offY;if(nx<0||nx>=COLS||ny>=ROWS||(ny>=0&&board[ny][nx]))return true}return false;}
  function rotateMatrix(m){return m[0].map((_,i)=>m.map(r=>r[i]).reverse());}
  function move(dx){if(state!=="running")return;if(!collision(piece,dx,0)){piece.x+=dx;audio.move();draw();}}
  function rotate(){if(state!=="running")return;const r=rotateMatrix(piece.matrix);for(const kick of [0,-1,1,-2,2])if(!collision(piece,kick,0,r)){piece.matrix=r;piece.x+=kick;audio.rotate();draw();return;}}
  function softDrop(){if(state!=="running")return;if(!collision(piece,0,1)){piece.y++;score++;updateHud();}else lockPiece();dropTimer=0;}
  function hardDrop(){if(state!=="running")return;let d=0;while(!collision(piece,0,1)){piece.y++;d++;}score+=d*2;lockPiece();}
  function hold(){if(state!=="running"||!canHold)return;audio.rotate();const old=piece.type;if(holdPiece){piece=makePiece(holdPiece);holdPiece=old}else{holdPiece=old;piece=nextPiece;nextPiece=makePiece()}canHold=false;drawPreviews();}
  function lockPiece(){let above=false;for(let y=0;y<piece.matrix.length;y++)for(let x=0;x<piece.matrix[y].length;x++)if(piece.matrix[y][x]){const by=piece.y+y,bx=piece.x+x;if(by<0)above=true;else board[by][bx]=piece.type;}if(above){gameOver();return;}audio.lock();clearLines();piece=nextPiece;nextPiece=makePiece();canHold=true;if(collision())gameOver();drawPreviews();}
  function clearLines(){let n=0;for(let y=ROWS-1;y>=0;y--){if(board[y].every(Boolean)){board.splice(y,1);board.unshift(Array(COLS).fill(""));n++;y++;}}if(n){const gains=[0,100,300,500,800];score+=gains[n]*level;lines+=n;level=Math.floor(lines/10)+1;best=Math.max(best,score);localStorage.setItem("dannyboy-tetris-best",String(best));audio.clear(n);vibrate(20+n*10);els.flash.classList.remove("go");void els.flash.offsetWidth;els.flash.classList.add("go");}updateHud();}
  function updateHud(){els.score.textContent=String(score).padStart(6,"0");els.best.textContent=String(Math.max(best,score)).padStart(6,"0");els.lines.textContent=String(lines).padStart(3,"0");els.level.textContent=String(level).padStart(2,"0");}
  function block(c,x,y,size,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=COLORS[c];ctx.fillRect(x+1,y+1,size-2,size-2);ctx.fillStyle="rgba(255,255,255,.45)";ctx.fillRect(x+2,y+2,size-4,Math.max(3,size*.14));ctx.fillRect(x+2,y+2,Math.max(3,size*.14),size-4);ctx.fillStyle="rgba(0,0,0,.28)";ctx.fillRect(x+3,y+size-5,size-6,3);ctx.fillRect(x+size-5,y+3,3,size-6);ctx.restore();}
  function resizeCanvas(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
  function drawGrid(){const w=canvas.clientWidth,h=canvas.clientHeight,cw=w/COLS,ch=h/ROWS;ctx.fillStyle="#050b1c";ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(86,139,215,.12)";ctx.lineWidth=1;for(let x=1;x<COLS;x++){ctx.beginPath();ctx.moveTo(x*cw,0);ctx.lineTo(x*cw,h);ctx.stroke()}for(let y=1;y<ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*ch);ctx.lineTo(w,y*ch);ctx.stroke()}return{cw,ch};}
  function drawPiece(p,cw,ch,ghost=false){p.matrix.forEach((row,y)=>row.forEach((v,x)=>{if(v&&p.y+y>=0)block(p.type,(p.x+x)*cw,(p.y+y)*ch,Math.min(cw,ch)+.7,ghost?.2:1)}));}
  function draw(){if(!canvas.clientWidth)return;const{cw,ch}=drawGrid();board.forEach((row,y)=>row.forEach((c,x)=>c&&block(c,x*cw,y*ch,Math.min(cw,ch)+.7)));if(piece&&state!=="welcome"&&state!=="over"){const ghost={...piece,y:piece.y,matrix:piece.matrix};while(!collision(ghost,0,1))ghost.y++;drawPiece(ghost,cw,ch,true);drawPiece(piece,cw,ch);}}
  function drawMini(context,type){const c=context.canvas,w=c.width,h=c.height;context.clearRect(0,0,w,h);if(!type)return;const m=SHAPES[type],s=22,ox=(w-m[0].length*s)/2,oy=(h-m.length*s)/2;context.save();m.forEach((r,y)=>r.forEach((v,x)=>{if(v){context.fillStyle=COLORS[type];context.fillRect(ox+x*s+1,oy+y*s+1,s-2,s-2);context.fillStyle="rgba(255,255,255,.4)";context.fillRect(ox+x*s+3,oy+y*s+3,s-6,4);context.fillStyle="rgba(0,0,0,.25)";context.fillRect(ox+x*s+3,oy+y*s+s-6,s-6,3)}}));context.restore();}
  function drawPreviews(){drawMini(nextCtx,nextPiece?.type);drawMini(holdCtx,holdPiece);}
  function tick(time){const dt=Math.min(80,time-lastTime||0);lastTime=time;if(state==="running"){dropTimer+=dt;const speed=Math.max(95,850-(level-1)*65);if(dropTimer>=speed){dropTimer=0;if(!collision(piece,0,1))piece.y++;else lockPiece();}draw();}raf=requestAnimationFrame(tick);}
  function startGame(){audio.unlock();board=emptyBoard();bag=[];score=0;lines=0;level=1;holdPiece="";piece=makePiece();nextPiece=makePiece();canHold=true;state="running";dropTimer=0;lastTime=performance.now();els.over.classList.remove("open");els.pause.classList.remove("open");els.rank.classList.remove("open");els.nameModal.classList.remove("open");els.message.classList.add("hidden");updateHud();drawPreviews();draw();}
  function pause(show=true){if(state==="running"){state="paused";if(show)els.pause.classList.add("open");els.message.textContent="PAUSED";els.message.classList.remove("hidden");}else if(state==="paused"){state="running";lastTime=performance.now();els.pause.classList.remove("open");els.message.classList.add("hidden");}}
  async function gameOver(){if(state==="over")return;state="over";audio.over();vibrate(90);best=Math.max(best,score);localStorage.setItem("dannyboy-tetris-best",String(best));updateHud();els.final.textContent=String(score);els.status.textContent="正在提交成绩…";els.over.classList.add("open");draw();try{await submitScore();els.status.textContent="成绩已进入排行榜！";}catch{els.status.textContent="成绩已保存在本机，联网后可再次挑战提交。";}}
  async function api(path,options={}){const url=API_BASE+path;const r=await fetch(url,options);if(!r.ok)throw new Error("request failed");return r.json();}
  async function submitScore(){return api("/api/scores",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerId,name:playerName,score,lines,level})});}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
  async function showRanks(){rankWasRunning=state==="running";if(rankWasRunning){state="paused";els.message.textContent="PAUSED";els.message.classList.remove("hidden");}els.rank.classList.add("open");els.rankList.innerHTML='<li class="loading">正在读取排行榜…</li>';try{const data=await api("/api/scores");els.rankList.innerHTML=(data.scores||[]).map((r,i)=>`<li class="${r.playerId===playerId?'me':''}"><span>${i<3?["🥇","🥈","🥉"][i]:String(i+1).padStart(2,"0")}　${esc(r.name)}</span><span class="rank-score">${Number(r.score).toLocaleString()}</span></li>`).join("")||'<li class="loading">还没有成绩，等你成为第一名！</li>';}catch{els.rankList.innerHTML='<li class="loading">排行榜暂时无法连接，请稍后再试。</li>';}}
  function closeRanks(){els.rank.classList.remove("open");if(rankWasRunning&&state==="paused"){state="running";lastTime=performance.now();els.message.classList.add("hidden");}rankWasRunning=false;}
  function saveName(){const name=$("nameInput").value.trim().replace(/\s+/g," ").slice(0,16);if(!name){$("nameInput").focus();return;}playerName=name;if(!playerId)playerId=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).slice(0,64);localStorage.setItem("dannyboy-tetris-name",name);localStorage.setItem("dannyboy-tetris-id",playerId);els.player.textContent=name;startGame();}
  function setSound(){soundOn=!soundOn;localStorage.setItem("dannyboy-tetris-sound",soundOn?"on":"off");els.sound.textContent=soundOn?"🔊":"🔇";if(soundOn)audio.unlock();}
  const action={left:()=>move(-1),right:()=>move(1),rotate,down:softDrop,drop:hardDrop,hold};
  document.addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","Space"].includes(e.code))e.preventDefault();audio.unlock();if(e.code==="ArrowLeft")move(-1);else if(e.code==="ArrowRight")move(1);else if(e.code==="ArrowUp"||e.code==="KeyX")rotate();else if(e.code==="ArrowDown")softDrop();else if(e.code==="Space")hardDrop();else if(e.code==="KeyC")hold();else if(e.code==="KeyP"||e.code==="Escape")pause();});
  document.querySelectorAll("[data-action]").forEach(btn=>{let timer=0;const run=()=>action[btn.dataset.action]?.();btn.addEventListener("pointerdown",e=>{e.preventDefault();audio.unlock();run();if(["left","right","down"].includes(btn.dataset.action))timer=setInterval(run,105);});const stop=()=>{clearInterval(timer);timer=0};btn.addEventListener("pointerup",stop);btn.addEventListener("pointercancel",stop);btn.addEventListener("pointerleave",stop);});
  $("startBtn").onclick=saveName;$("nameInput").addEventListener("keydown",e=>{if(e.key==="Enter")saveName()});$("againBtn").onclick=startGame;$("rankPlayBtn").onclick=startGame;$("rankBtn").onclick=showRanks;$("resultRankBtn").onclick=showRanks;$("closeRankBtn").onclick=closeRanks;$("soundBtn").onclick=setSound;$("pauseBtn").onclick=()=>pause();$("resumeBtn").onclick=()=>pause();$("restartBtn").onclick=startGame;
  document.addEventListener("visibilitychange",()=>{if(document.hidden&&state==="running")pause(false)});
  window.addEventListener("resize",resizeCanvas,{passive:true});window.addEventListener("orientationchange",()=>setTimeout(resizeCanvas,100));
  best=Number(localStorage.getItem("dannyboy-tetris-best"))||0;els.sound.textContent=soundOn?"🔊":"🔇";els.best.textContent=String(best).padStart(6,"0");if(playerName){$("nameInput").value=playerName;els.player.textContent=playerName;els.nameModal.querySelector("p:not(.eyebrow)").textContent=`欢迎回来，${playerName}！点击开始继续挑战排行榜。`;}
  resizeCanvas();raf=requestAnimationFrame(tick);if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));
})();
